spring :
    servlet :
        multipart :
            max-file-size :    10MB
            max-request-size : 10MB
    datasource :

        # PostgreSQL
#        url :      jdbc:postgresql://localhost:5432/fitnex
        #

        # MySQL
        url :      jdbc:mysql://localhost:3306/fitnex
        #

        username : root
        password : root
    jpa :
        hibernate :
            ddl-auto : update
        show-sql : true



server :
    port : 8080
